Fix gateway 03
picoservicess/intaniaOverflow pull request #26
Opened 2024-10-31 17:02 UTC by JinnySarita

add api-gateway for noti-service, reply-service

2024-10-31 17:22 UTC, sarunnut1236 requested changes
ตั้งชื่อ PR กำกวมค้าบเตง

2024-10-31 18:54 UTC, JinnySarita commented
> ตั้งชื่อ PR กำกวมค้าบเตง

แก้แล้วค้าบเตง

2024-10-31 18:59 UTC, JinnySarita commented
> ตั้งชื่อ PR กำกวมค้าบเตง

แก้แล้วค้าบเตง

2024-11-01 15:00 UTC, sarunnut1236 approved these changes
โค้ดใช้งานได้แล้ว โอเค ลุย!

2024-11-01 15:00 UTC, sarunnut1236 commented on notification-service/src/controllers/notificationController.ts
> +  console.log("mark!!")
delete consolelog jraaa

2024-11-01 15:08 UTC, ThanatWongsamut requested changes
Left some comment

2024-11-01 15:08 UTC, ThanatWongsamut commented on .github/workflows/lint.yml
> +  # pull_request:
Why we need to comment na @JinnySarita @sarunnut1236

2024-11-01 15:08 UTC, ThanatWongsamut commented on api-gateway/src/routes/notification-route.ts
> +        console.log(`${NOTIFICATION_SERVICE_URL}/notifications/health-check`);
Don't need to log

2024-11-01 15:08 UTC, ThanatWongsamut commented on api-gateway/src/routes/notification-route.ts
> +        console.log(`${NOTIFICATION_SERVICE_URL}/notifications`);
Same as before, Don't need to log

2024-11-01 15:08 UTC, ThanatWongsamut commented on api-gateway/src/routes/notification-route.ts
> +        console.log(`${NOTIFICATION_SERVICE_URL}/notifications/unread`);
Same as before, Don't need to log

2024-11-01 15:08 UTC, ThanatWongsamut commented on api-gateway/src/routes/notification-route.ts
> +        console.log(`${NOTIFICATION_SERVICE_URL}/notifications`);
Same as before, Don't need to log

2024-11-01 15:08 UTC, ThanatWongsamut commented on api-gateway/src/routes/reply-route.ts
> +        console.log(`${REPLY_SERVICE_URL}/replies/health-check`);
Same as before, Don't need to log

2024-11-01 15:08 UTC, ThanatWongsamut commented on notification-service/src/repositories/notificationRepository.ts
> -    if (result.modifiedCount === 0) {
Why we need to remove this

2024-11-01 15:10 UTC, sarunnut1236 commented on .github/workflows/lint.yml
> +  # pull_request:
มันรัน prettier 2 รอบอ่ะ เลยเอาออกอันนึง

2024-11-01 16:54 UTC, JinnySarita commented on notification-service/src/controllers/notificationController.ts
> +  console.log("mark!!")
done kaa

2024-11-01 16:54 UTC, JinnySarita commented on api-gateway/src/routes/notification-route.ts
> +        console.log(`${NOTIFICATION_SERVICE_URL}/notifications/health-check`);
done kaa

2024-11-01 16:54 UTC, JinnySarita commented on api-gateway/src/routes/notification-route.ts
> +        console.log(`${NOTIFICATION_SERVICE_URL}/notifications`);
done kaa

2024-11-01 16:54 UTC, JinnySarita commented on api-gateway/src/routes/notification-route.ts
> +        console.log(`${NOTIFICATION_SERVICE_URL}/notifications/unread`);
done kaa

2024-11-01 16:54 UTC, JinnySarita commented on api-gateway/src/routes/notification-route.ts
> +        console.log(`${NOTIFICATION_SERVICE_URL}/notifications`);
done kaa

2024-11-01 16:54 UTC, JinnySarita commented on api-gateway/src/routes/reply-route.ts
> +        console.log(`${REPLY_SERVICE_URL}/replies/health-check`);
done kaa

2024-11-01 16:55 UTC, JinnySarita commented on notification-service/src/repositories/notificationRepository.ts
> -    if (result.modifiedCount === 0) {
That code throws an error if no notifications are found to update, which results in a 500 error. But in reality, this isn’t an error—it just means there was nothing to update. Returning a 204 No Content makes more sense and avoids confusion, letting the client know that everything’s working as expected, even if there’s nothing new to update.

2024-11-02 07:53 UTC, ThanatWongsamut approved these changes
Nice

2024-11-02 07:53 UTC, merged